#!/usr/bin/env node
/**
 * Regenerate every token of a captured session with the token generator and compare it with the captured one, byte for byte.
 *
 *   node regenerate-tokens.js <session.json> [--verbose]
 *
 * The generator gets only its inputs (token-generator.js: SESSION_INPUTS and REQUEST_INPUTS, read from the capture by
 * capture-inputs.js); all computed fields must come out equal. Exits with 1 when any token differs.
 */
const fs = require("node:fs");
const {decodeToken} = require("../token-verifier/token-verifier");
const {TokenGenerator} = require("../token-verifier/token-generator");
const {inputsFromCapture} = require("../token-verifier/capture-inputs");

const args = process.argv.slice(2);
const [input] = args.filter(a => !a.startsWith("--"));
if (!input) {
    console.error("Usage: regenerate-tokens.js <session.json> [--verbose]");
    process.exit(2);
}
const {session, requests, rows} = inputsFromCapture(JSON.parse(fs.readFileSync(input, "utf8")));
const generator = new TokenGenerator(session);
let matched = 0;
requests.forEach((request, i) => {
    const {value} = generator.next(request);
    const captured = Buffer.from(rows[i].token.value, "base64").toString("base64");
    if (value === captured) return void matched++;
    const a = decodeToken(value).fields, b = rows[i].fields;
    const differing = [...new Set([...Object.keys(a), ...Object.keys(b)])].filter(k => String(a[k]) !== String(b[k])).join(", ");
    console.log(`#${rows[i].index} ${request.kind} ${request.url.slice(0, 50)}: differs in ${differing || "the header or SST"}`);
});
console.log(`${matched}/${requests.length} tokens regenerated byte for byte (site build ${session.headerByte}, script start ${new Date(session.start).toISOString()})`);
process.exit(matched === requests.length ? 0 : 1);
